CREATE TYPE adchoices AS ENUM ('None', 'Homepage ads', 'Popup ads', 'Annoying Ads');

CREATE TABLE products (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,

    title text not null unique,
    creator_id INTEGER REFERENCES users(id) not null,
    description text,
    price NUMERIC(15,4),
    sold INTEGER DEFAULT 0,
    profit NUMERIC(20,4) DEFAULT 0,
    ad adchoices default 'None',
    date_created TIMESTAMP DEFAULT now() NOT NULL
);