CREATE TYPE adchoices AS ENUM ('None', 'Homepage ads', 'Popup ads', 'Annoying ads');

CREATE TABLE products (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    img text,
    title text not null unique,
    creator_id INTEGER REFERENCES users(id) not null,
    description text,
    price NUMERIC(15,2),
    sold INTEGER DEFAULT 0,
    profit NUMERIC(20,2) DEFAULT 0,
    ad adchoices default 'None',
    date_created TIMESTAMP DEFAULT now() NOT NULL
);