CREATE TABLE purchased_products (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    product_id INTEGER REFERENCES products(id) not null,
    buyer_id INTEGER REFERENCES users(id) not null,
    bonus NUMERIC(15,2) default 0,
    date_created TIMESTAMP DEFAULT now() NOT NULL
);